export class Entry {
    key: string; 
    // use firebase autogenerated key. no need to provide this when saving data.
    title: string;
    text: string;
    // image: string;
    timeStamp: Date;
    // better choice of using setter and getter
}